apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: win-data-volume
spec:
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50G
    storageClassName: local-shared
  source:
    http:
      url: "https://storage.googleapis.com/rgreaves-gke-chaos-kubevirt/windows-generic.qcow2"
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50G
    storageClassName: local-shared
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: windows-generic-vm
    name: windows-generic-vm
  name: windows-generic-vm
spec:
  ## This is the real spec
  # running: false
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: windows-generic-vm
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          interfaces:
          - name: default
            masquerade: {}
          # inputs:
          # - type: tablet
          #   bus: virtio
          #   name: usb-drive
          disks:
            - disk:
                bus: sata
              name: win-data-volume-mount
              bootOrder: 1
            - name: virtiocontainerdisk
              cdrom:
                bus: sata
              bootOrder: 2
        resources:
          requests:
            memory: 8Gi
            cpu: 2
      networks:
      - name: default
        pod: {}
      # dnsPolicy: None
      # dnsConfig:
      #   nameservers:
      #   - 8.8.8.8
      volumes:
        - dataVolume:
            name: win-data-volume
          name: win-data-volume-mount
        - containerDisk:
            image: kubevirt/virtio-container-disk
          name: virtiocontainerdisk
