apiVersion: v1
kind: Namespace
metadata:
    name: scrape
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scrape-sa
  namespace: scrape
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services","pods","configmaps"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scrape-binding
subjects:
- kind: ServiceAccount
  name: scrape-sa
  namespace: scrape
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: scrape
  namespace: scrape
spec:
  serviceAccountName: scrape-sa
  containers:
  - name: scrape
    image: gcr.io/anthos-edge-361104/scrape
    imagePullPolicy: Always
    env:
    - name: GCP_PROJECT
      value: "anthos-edge-361104"
