apiVersion: v1
kind: Namespace
metadata:
  name: pos
  annotations:
    istio-injection: enabled istio.io/rev-
---
apiVersion: v1
kind: Service
metadata:
  name: pos
  namespace: pos
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9113'
spec:
  type: NodePort
  selector:
    app: pos
  ports:
  - protocol: TCP
    port: 80
    nodePort: 32321
---
apiVersion: v1
kind: Service
metadata:
  name: pos-metrics
  namespace: pos
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9113'
spec:
  type: ClusterIP
  selector:
    app: pos
  ports:
  - name: http
    port: 9113
    targetPort: 9113