apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: abm-europe-west1,abm-europe-west2,abm-europe-west3,abm-europe-west4,abm-europe-west6,abm-europe-west8,abm-europe-west9,abm-europe-southwest1,abm-southamerica-west1,abm-asia-northeast3,abm-asia-northeast2,abm-asia-northeast1,abm-southamerica-east1,abm-us-west2,abm-us-west3,abm-us-west1,abm-us-west4,abm-us-central1,abm-us-south1,abm-europe-central2,abm-asia-east2,abm-asia-east1,abm-asia-southeast2,abm-northamerica-northeast1,abm-northamerica-northeast2,abm-europe-north1,abm-asia-south1,abm-asia-south2,abm-us-east1,abm-us-east4,abm-australia-southeast1
    prometheus.io/port: '9113'
    prometheus.io/scrape: 'true'
  name: pos
  namespace: pos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos
  template:
    metadata:
      labels:
        app: pos
    spec:
      containers:
      - image: gcr.io/anthos-edge-361104/pos:v1
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
        name: pos
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
      - args:
        - -nginx.scrape-uri=http://127.0.0.1/nginx_status
        image: nginx/nginx-prometheus-exporter:0.10.0
        name: nginx-exporter
        ports:
        - containerPort: 9113
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
