apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos
  namespace: pos
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9113'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos
  template:
    metadata:
      labels:
        app: pos
    spec:
      containers:
      - name: pos
        image: gcr.io/anthos-edge-361104/pos:v1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.10.0
        args:
        - -nginx.scrape-uri=http://127.0.0.1/nginx_status
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 9113
