apiVersion: v1
kind: Service
metadata:
  name: prometheus-external-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector:
      app: prometheus
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector:
      app: prometheus
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 9090